    "userID" : "JBSOolvtoH",
    "firstName" : "Vishal",
    "lastName" : "Chauhan",
    "companyEmail" : "vishalchouhannainpur@gmail.com" ,
    "reasonForLeave" : "leave",
    "startDate" : "12-04-23",
    "endDate" : "15-04-23",
    "supervisorName" : "Kaushal",
    "typeOfLeave" : "Personal",
    "pendingTaskDetails" : "sdfad",
    "discussWithSupervisor" : "adfjklds",
    "comments" : "askldfdsja"